/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DsaIndexRouteImport } from './routes/dsa/index'
import { Route as DsaProblemIdRouteImport } from './routes/dsa/$problemId'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DsaIndexRoute = DsaIndexRouteImport.update({
  id: '/dsa/',
  path: '/dsa/',
  getParentRoute: () => rootRouteImport,
} as any)
const DsaProblemIdRoute = DsaProblemIdRouteImport.update({
  id: '/dsa/$problemId',
  path: '/dsa/$problemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/skills': typeof SkillsRoute
  '/tools': typeof ToolsRoute
  '/dsa/$problemId': typeof DsaProblemIdRoute
  '/dsa': typeof DsaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/skills': typeof SkillsRoute
  '/tools': typeof ToolsRoute
  '/dsa/$problemId': typeof DsaProblemIdRoute
  '/dsa': typeof DsaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/skills': typeof SkillsRoute
  '/tools': typeof ToolsRoute
  '/dsa/$problemId': typeof DsaProblemIdRoute
  '/dsa/': typeof DsaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/projects'
    | '/skills'
    | '/tools'
    | '/dsa/$problemId'
    | '/dsa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/projects'
    | '/skills'
    | '/tools'
    | '/dsa/$problemId'
    | '/dsa'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/projects'
    | '/skills'
    | '/tools'
    | '/dsa/$problemId'
    | '/dsa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  SkillsRoute: typeof SkillsRoute
  ToolsRoute: typeof ToolsRoute
  DsaProblemIdRoute: typeof DsaProblemIdRoute
  DsaIndexRoute: typeof DsaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsa/': {
      id: '/dsa/'
      path: '/dsa'
      fullPath: '/dsa'
      preLoaderRoute: typeof DsaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsa/$problemId': {
      id: '/dsa/$problemId'
      path: '/dsa/$problemId'
      fullPath: '/dsa/$problemId'
      preLoaderRoute: typeof DsaProblemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  SkillsRoute: SkillsRoute,
  ToolsRoute: ToolsRoute,
  DsaProblemIdRoute: DsaProblemIdRoute,
  DsaIndexRoute: DsaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
